name: Daily CEO News Sentiment

on:
  schedule:
    - cron: "0 12 * * *"         # ~8am ET
  workflow_dispatch:
  push:
    paths:
      - 'news_sentiment_ceos.py'
      - 'ceo_aliases.csv'
      - 'ceos.txt'
      - '.github/workflows/daily_ceos.yml'

permissions:
  contents: write

# Prevent overlapping runs
concurrency:
  group: daily-ceos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
      TZ: America/New_York

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies (if requirements.txt exists)
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure CEO data folders exist
        run: mkdir -p data_ceos/articles

      - name: Run daily CEO sentiment
        run: python news_sentiment_ceos.py

      - name: Commit & push changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore(data_ceos): update CEO news sentiment for $(date -u +%F)"
            git pull --rebase --autostash || true
            git push
          else
            echo "No changes to commit."
          fi
