name: Daily News Sentiment

on:
  schedule:
    - cron: "0 12 * * *"   # ~8am ET during DST (12:00 UTC)
  workflow_dispatch:
  push:
    paths:
      - 'news_sentiment.py'
      - 'requirements.txt'
      - 'aliases.csv'
      - 'brands.txt'
      - 'dashboard.html'
      - '.github/workflows/daily.yml'

permissions:
  contents: write

# Avoid overlapping schedule/manual/push runs
concurrency:
  group: daily-news-sentiment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
      TZ: America/New_York   # aligns commit-msg date with your ET ops

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies (if requirements.txt exists)
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data folders exist
        run: mkdir -p data/articles

      - name: Run daily sentiment (if script exists)
        if: ${{ hashFiles('news_sentiment.py') != '' }}
        env:
          KIT_API_KEY: ${{ secrets.KIT_API_KEY }}
          KIT_TAG_ID: ${{ secrets.KIT_TAG_ID }}
        run: python news_sentiment.py

      - name: Commit & push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if [[ -n $(git status --porcelain) ]]; then
            git add -A                          # includes deletions from purge
            git commit -m "chore(data): update daily news sentiment for $(date +%F)"
            git pull --rebase --autostash || true
            git push
          else
            echo "No changes to commit."
          fi

      # Optional: keep a copy of outputs with this run for quick inspection
      - name: Upload data artifact (for debugging)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: data-${{ github.run_id }}
          path: |
            data/daily_counts.csv
            data/articles/*.csv
          if-no-files-found: ignore
